### ISSUE TITLE
[tts_node-1] ModuleNotFoundError: No module named 'simple_node'

### ISSUE THREAD

**Issue by farbod-new** [MERLIN2-ARCH/text_to_speech#1]
Hi, 

I get the following error when trying to run this demo's launch file.

```
$ ros2 launch text_to_speech text_to_speech.launch.py
[INFO] [launch]: All log files can be found below /home/ff0002/.ros/log/2023-09-06-11-35-44-906100-OKTN264-50NDR52-982624
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tts_node-1]: process started with pid [982626]
[tts_node-1] Traceback (most recent call last):
[tts_node-1]   File "/home/ff0002/lm_ws/install/text_to_speech/lib/text_to_speech/tts_node", line 11, in <module>
[tts_node-1]     load_entry_point('text-to-speech==0.0.0', 'console_scripts', 'tts_node')()
[tts_node-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
[tts_node-1]     return get_distribution(dist).load_entry_point(group, name)
[tts_node-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
[tts_node-1]     return ep.load()
[tts_node-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
[tts_node-1]     return self.resolve()
[tts_node-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
[tts_node-1]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[tts_node-1]   File "/home/ff0002/lm_ws/install/text_to_speech/lib/python3.8/site-packages/text_to_speech/tts_node.py", line 11, in <module>
[tts_node-1]     from simple_node import Node
[tts_node-1] ModuleNotFoundError: No module named 'simple_node'
[ERROR] [tts_node-1]: process has died [pid 982626, exit code 1, cmd '/home/ff0002/lm_ws/install/text_to_speech/lib/text_to_speech/tts_node --ros-args -r __node:=tts_node -r __ns:=/text_to_speech'].

```
Any help about how I can resolve this is greatly appreciated.

Thanks

**Comment by gitisacatsname** [comment]
git clone https://github.com/uleroboticsgroup/simple_node.git in ws/src
